using RayTracer.Core.Scenes;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

namespace RayTracer.Core.Graphics;

/// <summary>
/// Static class for rendering a <see cref="Scene"/>, using it's <see cref="Scene.Camera"/>.
/// </summary>
/// <remarks>
/// Uses the rays generated by the <see cref="Camera"/>, and objects in the <see cref="Scene"/> to create the output image
/// </remarks>
public static class Renderer
{
	public static Image<Rgb24> Render(Scene scene)
	{
		
	}
}